# -*- coding: utf-8 -*-
"""least_squares

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1QJ99tKCQbHOqoEKu4GDic204SJmMhlK3
"""

#Import libraries
import numpy as np
import scipy as sp

# Prepare matrices to solve equation
X = np.matrix([[2100,3,20],[2500,4,15],[1800,2,30],[2200,3,25]])
prices = np.matrix([460,540,330,400])
y = prices.T

# Solve the equation
beta, residuals, rank, singular_values = sp.linalg.lstsq(X,y)

# Use beta to predict the dot product for new inputs
new_data = np.array([2400,3,20])
predicted = np.dot(new_data, beta)
print(f'The predicted price using least squares is ${predicted}')