# -*- coding: utf-8 -*-
"""pagerank

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1upHkqvGnvOmSUIumAN_1bWKw_W09Wc7s
"""

# Import libraries
import scipy as sp
import numpy as np

# Create Matrix and display
M = np.matrix([[0,0,1/2,0], [1/3,0,0,1/2], [1/3,1/2,0,1/2], [1/3,1/2,1/2,0]])
print('Matirx:\n', M, '\n')
# Find eigenvalues and eigenvectors
eigenvalues, eigenvectors = sp.linalg.eig(M)

#Find the dominant eigenvecror using dominant eigenvalue
dominant_eigenvalue = eigenvalues[np.argmax(abs(eigenvalues))]
dominant_eigenvector = eigenvectors[:,np.argmax(abs(eigenvalues))]

# Normalize dominant eigenvector
n_dominant = dominant_eigenvector/np.sum(dominant_eigenvector)

# Display dominant eigenvalue
print('Dominant Eigenvector:\n', dominant_eigenvector,'\n')

# Create inital rank vector of ones
v = np.ones((4,1))

# Find difference between intial vector and first transition
diff = np.abs(v - np.dot(M,v))

# Initialize iteration count
i = 0

# Loop through transition steps until convergence of all entries
while not np.all(diff < 10 ** -10):
    v = np.dot(M,v)
    diff = np.abs(v - np.dot(M,v))
    i += 1

# Normalize vector found at end of convergence
v = np.array(np.dot(M,v))
norm_v = v/np.sum(v)

# Display final vector, normalized vector, normailed dominant eigenvector,
# and iteration count
print('PageRank:\n', v, '\n')
print('Normalized PageRank:\n', norm_v,'\n')
print('Normalized Dominant Eigenvector:\n', n_dominant,'\n')
print('Iterations:', i)

