# -*- coding: utf-8 -*-
"""pca

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1cJF2Kn6u31AZ5WsBrsa3lClh8MXO3PBC
"""

# Import libraries
import scipy as sp
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

# Convert csv to matrix
df = pd.read_csv("data.csv")
data = df.to_numpy()

# Create covariance matrix of data
cov_m = np.cov(data, rowvar = False)

# Find eigenvalues and eigenvalue decompostion of covariance matrix and display
eigenvalues,eigen_decomp = sp.linalg.eigh(cov_m)
print('Eigenvalues:\n', eigenvalues,'\n')
print('Eigenvalue Decompostion: \n',eigen_decomp,'\n')

#Use dominant eigenvalue to find principal component and display
dominant_eigenvalue = eigenvalues[np.argmax(abs(eigenvalues))]
principal_component = eigen_decomp[:,np.argmax(abs(eigenvalues))]
print('Dominant Eigenvalue:', dominant_eigenvalue,'\n')
print('Principal Component:\n', principal_component,'\n')

# Project data along principal component
projected_data = np.dot(data,principal_component)

# Plot 2D data
plt.scatter(data[:, 0], data[:, 1],label='Original Data', alpha=0.7,linewidths= .5, color='blue')
plt.xlabel('Height')
plt.ylabel('Weight')
plt.title('Height vs Weight(Standardized)')
plt.legend()
plt.grid(True)
plt.savefig('original_data.png')
plt.show()

# Plot 1D projection
plt.figure(figsize=(8, 2))
plt.scatter(projected_data, np.zeros_like(projected_data), label='1D Projected Data', alpha=0.7, color='purple')
plt.xlabel('Projected Dimension 1')
plt.title('1D Projection on a Single Axis')
plt.yticks([]) # Hide y-axis ticks for a cleaner 1D representation
plt.legend()
plt.grid(True)
plt.savefig('one_d_data.png')
plt.show()